config/routes.rb
Kintore::Application.routes.draw do

  root 'front/top#index'
  scope module: :front do
    post 'login' => 'sessions#login', as: :login
    get  'logout' => 'sessions#logout', as: :logout


    resources :menus, only: :index
    resources :users
    resources :sessions
  end

  namespace :admin do
    get 'login' => 'sessions#login', as: :login
    get 'logout' => 'sessions#logout', as: :logout


    resources :sessions, only: :create
    resources :users
    resources :trainings
    resources :menus
  end
end

app/models/training.rb
class Training < ActiveRecord::Base

  validates :name, presence:true
  validates :description,
            presence: true,
            

  validates :url,
            presence: true

  validates :part,
            numericality:{
              only_integer: true,greater_than_or_equal_to:1,less_than_or_equal_to:6
            }
end

app/controllers/admin/trainings_controller.rb
class Admin::TrainingsController < AdminController
  def index
    @trainings = Training.all
  end

  def new
    @training = Training.new
  end

  def edit
    @training = Training.find_by_id(params[:id])
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      flash[:notice] = ["success", "作成しました。"]
      redirect_to admin_trainings_path
    else
      flash[:notice] = ["error", "失敗しました。"]
      redirect_to new_admin_training_path
    end
  end

  def update
    @training = Training.find_by_id(training_params[:id])
    @training.attributes = training_params
    if @training.save
      flash[:notice] = ["success", "作成しました。"]
      redirect_to admin_trainings_path
    else
      flash[:notice] = ["error", "失敗しました。"]
      redirect_to edit_admin_training_path
    end
  end

  def destroy
    @training = Training.find_by_id(params[:id])
    @training.destroy
    flash[:notice] = ["success", "削除しました。"]
    redirect_to admin_trainings_path
  end

  private
    def training_params
      params.require(:training).permit!()
    end
end

app/views/admin/trainings/_form.html.erb
<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">トレーニング名<span class="required">*</span></label>
    <div class="col-md-4">
        <%= f.text_field :name, class: "form-control",placeholder: "トレーニング名" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">トレーニング詳細<span class="required">*</span></label>
    <div class="col-md-5">
        <%= f.text_area :description, class: "form-control maxlength-handler", size: "20x8" ,placeholder: "トレーニング詳細" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">URL1<span class="required">*</span></label>
    <div class="col-md-4">
        <%= f.text_field :url, class: "form-control",placeholder: "URL" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">URL2</label>
    <div class="col-md-4">
        <%= f.text_field :url2, class: "form-control",placeholder: "URL2" %>
        <div class="form-control-focus"> </div>
    </div>
</div>


<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">部位<span class="required">*</span></label>
    <div class="col-md-4">
        <div class="md-radio-inline">

            <div class="md-radio">
                <%= f.radio_button :part, PART[:arm], checked: @training.try(:part) == PART[:arm],class: "md-radiobtn" %>
                <label for="training_part_1">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>腕
                </label>
            </div>
            <div class="md-radio">
                <%= f.radio_button :part, PART[:shoulder], checked: @training.try(:part) == PART[:shoulder],class: "md-radiobtn" %>
                <label for="training_part_2">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>肩
                </label>
            </div>
            <div class="md-radio">
                <%= f.radio_button :part, PART[:bust], checked: @training.try(:part) == PART[:bust],class: "md-radiobtn" %>
                <label for="training_part_3">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>胸
                </label>
            </div>

            <div class="md-radio">
                <%= f.radio_button :part, PART[:back], checked: @training.try(:part) == PART[:back],class: "md-radiobtn" %>
                <label for="training_part_4">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>背筋
                </label>
            </div>
            <div class="md-radio">
                <%= f.radio_button :part, PART[:abs], checked: @training.try(:part) == PART[:abs],class: "md-radiobtn" %>
                <label for="training_part_5">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>腹筋
                </label>
            </div>
            <div class="md-radio">
                <%= f.radio_button :part, PART[:leg], checked: @training.try(:part) == PART[:leg],class: "md-radiobtn" %>
                <label for="training_part_6">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>足
                </label>
            </div>
        </div>
    </div>
</div>

app/views/admin/trainings/edit.html.erb
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption font-green-haze">
                            <i class="icon-settings font-green-haze"></i>
                            <span class="caption-subject bold uppercase">トレーニング編集</span>
                        </div>
                    </div>
                    <%= form_for @training, url: {action: :update, controller: :trainings}, html: {id: 'training_form', class: 'training_form form-horizontal margin-bottom-40'} do |f| %>
                    <div class="portlet-body">
                        <%= render 'admin/trainings/form', f: f %>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn blue">編集する</button>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<% content_for(:javascript) do %>
<%= javascript_include_tag 'trainings/index' %>
<% end %>
<% content_for(:css) do %>
<%= stylesheet_link_tag 'trainings/index', media: "all" %>
<% end %>

app/views/admin/trainings/index.html.erb
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-social-dribbble font-green"></i>
                            <span class="caption-subject font-green bold uppercase">トレーニング一覧</span>
                        </div>

                        <div class="actions">
                            <a class="btn btn-circle btn-icon-only btn-default" href="<%= new_admin_training_path %>">
                                <i class="icon-wrench"></i>
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-scrollable">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>トレーニング名</th>
                                        <th>説明</th>
                                        <th>部位</th>
                                        <th>処理</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% if @trainings.present? %>
                                    <% @trainings.each do |training| %>
                                    <tr>
                                        <td><%= training.name %></td>
                                        <td><%= training.description %></td>
                                        <td><%= training.part %></td>
                                        <td>
                                            <%= link_to '編集', edit_admin_training_path(training), class: "label label-sm label-info" %>
                                            <%= link_to '削除', admin_training_path(training),method: :delete, class: "label label-sm label-danger" %>
                                        </td>
                                    </tr>
                                    <% end %>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/trainings/new.html.erb
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption font-green-haze">
                            <i class="icon-settings font-green-haze"></i>
                            <span class="caption-subject bold uppercase">トレーニング作成</span>
                        </div>
                    </div>
                    <%= form_for @training, url: {action: :create, controller: :trainings}, html: {id: 'training_form', class: 'training_form form-horizontal margin-bottom-40'} do |f| %>
                    <div class="portlet-body">
                        <%= render 'admin/trainings/form', f: f %>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn blue">登録する</button>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>