config/routes.rb
Kintore::Application.routes.draw do

  root 'front/top#index'
  scope module: :front do
    post 'login' => 'sessions#login', as: :login
    get  'logout' => 'sessions#logout', as: :logout


    resources :menus, only: :index
    resources :users
    resources :sessions
  end

  namespace :admin do
    get 'login' => 'sessions#login', as: :login
    get 'logout' => 'sessions#logout', as: :logout


    resources :sessions, only: :create
    resources :users
    resources :trainings
    resources :menus
  end
end

app/views/shared/admin/_error.html.erb
<% if flash[:notice] %>
  <div id="toastr" class="notice" data-status="<%= flash.now[:notice][0] %>"  data-msg="<%= flash.now[:notice][1] %>" data-url="<%= flash.now[:notice][2] %>"></div>
<% end %>

app/views/shared/admin/_footer.html.erb
<div class="page-footer">
    <div class="page-footer-inner"> 2015 &copy; Metronic by keenthemes.
        <a href="http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" title="Purchase Metronic just for 27$ and get lifetime updates for free" target="_blank">Purchase Metronic!</a>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

app/views/shared/admin/_header.html.erb
<div class="page-header-inner container">
    <div class="page-logo">
        <a href="<%= root_path %>">
            <img src="/images/admin/logo.png" alt="logo" class="logo-default" width="115" height="30" />
        </a>
        <div class="menu-toggler sidebar-toggler"></div>
    </div>

    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"></a>

    <div class="page-top">
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="icon-user"></i>
                        <span class="username username-hide-on-mobile"><%= current_admin.name %></span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>
                            <%= link_to edit_user_path(current_admin) do %>
                            <i class="icon-key"></i>プロフィール</a>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to [:logout] do %>
                            <i class="icon-key"></i> Log Out </a>
                            <% end %>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/shared/admin/_side.html.erb
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu  " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li>
                <a href="<%= admin_users_path %>">
                    <i class="fa-red icon-paper-plane"></i>
                    <span class="title">ユーザ一覧</span>
                    <span class="arrow "></span>
                </a>
            </li>
            <li>
                <a href="<%= admin_trainings_path %>">
                    <i class="fa-red icon-paper-plane"></i>
                    <span class="title">トレーニング一覧</span>
                    <span class="arrow "></span>
                </a>
            </li>
            <li>
                <a href="<%= admin_menus_path %>">
                    <i class="fa-red icon-paper-plane"></i>
                    <span class="title">メニュー一覧</span>
                    <span class="arrow "></span>
                </a>
            </li>
        </ul>
    </div>
</div>