config/routes.rb
Kintore::Application.routes.draw do

  root 'front/top#index'
  scope module: :front do
    post 'login' => 'sessions#login', as: :login
    get  'logout' => 'sessions#logout', as: :logout


    resources :menus, only: :index
    resources :users
    resources :sessions
  end

  namespace :admin do
    get 'login' => 'sessions#login', as: :login
    get 'logout' => 'sessions#logout', as: :logout


    resources :sessions, only: :create
    resources :users
    resources :trainings
    resources :menus
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  has_many :trainings, through: :training_menus
  has_many :training_menus, dependent: :destroy


  attr_accessor :training_attributes
  validates :name,
            presence: true,
            length: {maximum: 255}
  validates :description,
            presence: true,
            length: {maximum: 65535}

  validates :condition_sex, presence: true
  validates :condition_term, presence: true
  validates :condition_body_type, presence: true
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < AdminController
  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
    @trainings = Training.all
    @training_ids = []
  end

  def edit
    @menu = Menu.find_by_id(params[:id])
    @trainings = Training.all
    @training_ids = @menu.trainings.pluck(:id)
    @training_ids = @menu.trainings.present? ? @menu.trainings.pluck(:id) : []
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.trainings = menu_params[:training_attributes].present? ? Training.find(menu_params[:training_attributes]) : []
    if @menu.save
      flash[:notice] = ["success", "作成しました。"]
      #flash[:success] = ["success","作成しました"]
      redirect_to admin_menus_path
    else
      flash[:notice] = ["error", "失敗しました。"]
      #flash[:error] = ["error","失敗しました"]
      redirect_to new_admin_menu_path
    end
  end

  def update
    @menu = Menu.find_by_id(params[:id])
    @menu.attributes = menu_params
    @menu.trainings  = menu_params[:training_attributes].present? ? Training.find(menu_params[:training_attributes]) : []
    if @menu.save
      flash[:notice] = ["success", "作成しました。"]
      redirect_to admin_menus_path
    else
      flash[:notice] = ["error", "失敗しました。"]
      redirect_to edit_admin_menu_path
    end
  end

  def destroy
    @menu = Menu.find_by_id(params[:id])
    @menu.destroy
    redirect_to admin_menus_path
  end

  private
    def menu_params
      params.require(:menu).permit!()
    end
end

app/controllers/front/menus_controller.rb
class Front::MenusController < FrontController
  def index
    
  end
end

app/views/admin/menus/_form.html.erb
<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">メニュー名<span class="required">*</span></label>
    <div class="col-md-4">
        <%= f.text_field :name, class: "form-control",placeholder: "メニュー名" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">メニュー説明<span class="required">*</span></label>
    <div class="col-md-5">
        <%= f.text_area :description, class: "form-control maxlength-handler", size: "20x8" ,placeholder: "メニュー説明" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">性別条件<span class="required">*</span></label>
    <div class="col-md-4">
        <%= f.select :condition_sex, {'男' => 1 , '女' => 2}, class:"form-control" %>
        <div class="form-control-focus"> </div>
    </div>
</div>
<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">トレーニング可能日数<span class="required">*</span></label>
    <div class="col-md-4">
        <%= f.select :condition_term, {'週2' => 1 , '週3' =>2, '週4以上' => 3}, class: "form-control" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-md-2 control-label">目的<span class="required">*</span></label>
    <div class="col-md-4">
        <%= f.select :condition_body_type, {'筋力UP' => 1 , 'ダイエットor減量' =>2}, class: "form-control" %>
        <div class="form-control-focus"> </div>
    </div>
</div>

<div class="form-group form-md-line-input">
    <label class="col-xs-2 control-label form__label">トレーニング<span class="required">*</span></label>
    <div class="col-xs-7">
        <div class="form-md-checkboxes">
            <% if @trainings.present? %>
            <% @trainings.each do |training| %>
            <div class="md-checkbox">
                <%= f.check_box :training_attributes, {multiple: true,checked: @training_ids.include?(training.id), class: "md-check", include_hidden: false}, training.id %>
                <label for="menu_training_attributes_<%= training.id %>">
                    <span></span>
                    <span class="check"></span>
                    <span class="box"></span>
                    <%= training.name %>
                </label>
            </div>
            <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/menus/edit.html.erb
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption font-green-haze">
                            <i class="icon-settings font-green-haze"></i>
                            <span class="caption-subject bold uppercase">メニュー編集</span>
                        </div>
                    </div>
                    <%= form_for @menu, url: {action: :update, controller: :menus}, html: {id: 'menu_form', class: 'menu_form form-horizontal margin-bottom-40'} do |f| %>

                    <div class="portlet-body">
                        <%= render 'admin/menus/form' ,f: f %>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn blue">編集する</button>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/menus/index.html.erb
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-social-dribbble font-green"></i>
                            <span class="caption-subject font-green bold uppercase">メニュー一覧</span>
                        </div>

                        <div class="actions">
                            <a class="btn btn-circle btn-icon-only btn-default" href="<%= new_admin_menu_path %>">
                                <i class="icon-wrench"></i>
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-scrollable">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>メニュー名</th>
                                        <th>処理</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% if @menus.present? %>
                                    <% @menus.each do |menu| %>
                                    <tr>
                                        <td><%= menu.name %></td>
                                        <td>
                                            <%= link_to '編集', edit_admin_menu_path(menu), class: "label label-sm label-info" %>
                                            <%= link_to '削除', admin_menu_path(menu),method: :delete, class: "label label-sm label-danger" %>
                                        </td>
                                    </tr>
                                    <% end %>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/menus/new.html.erb
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption font-green-haze">
                            <i class="icon-settings font-green-haze"></i>
                            <span class="caption-subject bold uppercase">メニュー作成</span>
                        </div>
                    </div>
                    <%= form_for @menu, url: {action: :create, controller: :menus}, html: {id: 'menu_form', class: 'menu_form form-horizontal margin-bottom-40'} do |f| %>

                    <div class="portlet-body">
                        <%= render 'admin/menus/form' ,f: f %>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn blue">登録する</button>
                            </div>
                        </div>
                    </div>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>